/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface AppRoot {}
  interface AppStats {}
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes {}
  interface AppRoot extends JSXBase.HTMLAttributes {}
  interface AppStats extends JSXBase.HTMLAttributes {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'app-stats': AppStats;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {

  // Adding a global JSX for backcompatibility with legacy dependencies
  export namespace JSX {
    export interface Element {}
  }



  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppStatsElement extends Components.AppStats, HTMLStencilElement {}
  var HTMLAppStatsElement: {
    prototype: HTMLAppStatsElement;
    new (): HTMLAppStatsElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'app-stats': HTMLAppStatsElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

